name: A workflow is a configurable automated process made up of one or more jobs. You must create a YAML file to define your workflow configuration
on:
  workflow_dispatch:
    inputs:
      string_input1:
        description: 'A string input'
        default: 'default_value'
        required: false
        type: string
      boolean_input1:
        description: 'A boolean input'
        default: true
        required: true
        type: boolean
      choice_input1: 
        description: 'A choice input'
        type: choice
        required: true
        options:
          - us-west-1
          - us-west-2
          - us-east-1
          - eu-west-1
      environment1:
        description: 'Environment to run tests against'
        type: environment
        required: true
      string_input2:
        description: 'A string input'
        default: 'default_value'
        required: false
        type: string
      boolean_input2:
        description: 'A boolean input'
        default: true
        required: true
        type: boolean
      string_input:
        description: 'A string input'
        default: 'default_value'
        required: false
        type: string
      boolean_input:
        description: 'A boolean input'
        default: true
        required: true
        type: boolean
      choice_input: 
        description: 'A choice input'
        type: choice
        required: true
        options:
          - us-west-1
          - us-west-2
          - us-east-1
          - eu-west-1
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Print Inputs
      run: |
        echo "String Input: ${{ github.event.inputs.string_input }}"
        echo "Boolean Input: ${{ github.event.inputs.boolean_input }}"
        echo "Choice Input: ${{ github.event.inputs.choice_input }}"
        echo "Environment Input: ${{ github.event.inputs.environment }}"
